import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar";
import { Footer } from "./_components/footer";
import HamburgerMenu from "./_components/hamburgerMenu";
import { ClerkProvider, SignedIn } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { getAllSections } from "@/lib/queries";
import { BaseButton } from "./_atoms/buttons";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"], // Burada hatayı düzelttik
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const sections = await getAllSections("en");

  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased`}
        >
          <div className="hidden md:block">
            <Navbar />
          </div>
          <div className="block md:hidden">
            <HamburgerMenu />
          </div>

          <main>{children}</main>
          <SignedIn>
            <div className="fixed bottom-16 right-16 z-50">
              <Link href="/panel">
                <BaseButton className="bg-primary900 text-white hover:bg-primary 
                shadow-lg rounded-2xl">
                  <span className="p-6 text-lg">Create new content</span>
                </BaseButton>
              </Link>
            </div>
          </SignedIn>
          <Footer sections={sections} />
          {/* 🔔 Sonner Toaster */}
          <Toaster position="top-right" richColors closeButton />
        </body>
      </html>
    </ClerkProvider>
  );
}
