import { Geist, Geist_Mono, Merriweather } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";
import { Footer } from "./components/footer";
import HamburgerMenu from "./components/hamburgerMenu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"], // Burada hatayı düzelttik
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${merriweather.variable} antialiased`}
      >
          <div className="hidden md:block">
            <Navbar />
          </div>
          <div className="block md:hidden">
            <HamburgerMenu />
          </div>
        
          <main className="max-w-screen-xl mx-auto px-2 sm:px-2 md:px-8 lg:px-24 xl:px-48">{children}</main>
        <Footer />
        
      </body>
    </html>
  );
}